### ISSUE TITLE
References for motion calcs

### ISSUE THREAD

**Issue by mharms** [MRIMotionCorrection/parse_vNav_Motion#2]
I see that "rms" motion is calculated according to:
http://www.fmrib.ox.ac.uk/datasets/techrep/tr99mj1/tr99mj1/tr99mj1.html

Is there a reference for the "max" motion calculation?  It appears to be similar to the motion score in Tisdall et al. 2012 (MRM, 68:389-399), but not identical.  In particular, the definition of `t_rotmax` in `parse_vNav_Motion.py` is the same as the computation in Eq. (1) of the paper, but Eq. (3) from the paper would be simply:
`score = t_rotmax + np.linalg.norm(trans)`

Also curious, why the change from the assumption of a sphere of radius 64 mm in the 2012 (and Tisdall 2016) papers, to 100 mm in the current script?

**Comment by mdtisdall** [comment]
We need to expand the README to reference the relevant papers and explain the discrepancies.

**Comment by mharms** [comment]
So, you currently favor using the `--rms` metric, right?  (rms is what was used in the Reuter 2015 and Tisdall 2016 papers, with the caveat that the calculation in those papers assumed a radius of 64 mm, rather than 100 mm?)

**Comment by ericearl** [comment]
@mdtisdall I am also a little concerned about having a hard-coded 100 (mm) or 64 (mm) inside the code.  I just submitted a pull request here to correct allowing the user to specify their expected brain radius, but it would be good to know your recommended brain radius.  And if you don't like the idea of required brain radius as input, you could set a default option in the argparse and make it an optional field instead.

**Comment by mdtisdall** [comment]
@ericearl, thanks for submitting the PR to make the radius a command line argument, as well as the other improvements. Frankly, we haven't been consistent in picking a radius in previous publications and code, which is unfortunate. Hopefully making it explicit in this code will at least make it clear to users that they are picking a value for this parameter. Frankly, my experience is that the relative weighting of translations and rotations in the motion score, which is what the radius controls, doesn't seem to have significant practical impact on which TRs and which subjects are noted as "high motion". Of course, it does change the actual numerical outputs, so it's important we are explicit about it in the future.

**Comment by mdtisdall** [comment]
@mharms, thanks for your questions about this, and sorry for being slow getting back to you. I've now added references to the motion scores and tried to clarify their previous uses and derivations. Is there anything else you think should be in there or do you think this is clear enough now?

**Comment by mdtisdall** [comment]
Closed by PR #6
