### ISSUE TITLE
Packaging the script

### ISSUE THREAD

**Issue by hacevedo** [MRIMotionCorrection/parse_vNav_Motion#7]
Hi - I was curious if you'd be open to packaging the script so that it can more easily be used in other scripts/libraries? My group is hoping to get vNav motion included as an image quality metric in [mriqc](https://mriqc.readthedocs.io/en/latest/about.html) reports - so having this be an install-able dependency would be great!

**Comment by mdtisdall** [comment]
I'd be very keen to see this packaged for inclusion in other tools. I'm actually a pretty weak python developer, so have no idea what the current standards are for this or how to go about it. If there's an easy set of directions you can point me to, I'm happy to make the modifications when I get time. Alternatively, if it's easy for you to take on, please feel free to just do it.

**Comment by hacevedo** [comment]
Sure, I can take it on. Thanks!

**Comment by mdtisdall** [comment]
Closed by PR #8
